### ISSUE TITLE
Bringing this code in MLJ

### ISSUE THREAD

**Issue by tlienart** [tk3369/YeoJohnsonTrans.jl#1]
Hello!

We already have BoxCox transformation [here](https://github.com/alan-turing-institute/MLJModels.jl/blob/a23852efe6a87979f372f330d79dfd20c8309191/src/builtins/Transformers.jl#L411-L520) but this sounds like a cool transformation that could be added to the MLJ world, would you be potentially ok with this happening? (with creds to you). 

Cheers,
Thibaut

**Comment by tk3369** [comment]
Yes, I'm perfectly fine with that.  Let me know if you need any help transitioning.

**Comment by Sinansi** [comment]
@tlienart That is a great idea. Any updates on this issue?

**Comment by tlienart** [comment]
I haven't yet had the time to  do it but it should be easy to do, I might get to it this weekend :)

**Comment by Sinansi** [comment]
@tlienart That is a great news. Thanks for doing your best effort to improve MLJ.

**Comment by tk3369** [comment]
Hi @tlienart - I'm just cleaning up my repos lol. I suppose that this is already done so I'm closing this issue.
